{
 "title": "Amaroq",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "amaroq_results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"amaroq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"amaroq_runs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"critical\" or r[\"_field\"] == \"high\" or r[\"_field\"] == \"low\" or r[\"_field\"] == \"medium\" or r[\"_field\"] == \"total\")\n  |> group(columns: [\"_field\"])\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"amaroq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"amaroq_runs\")\n  //|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")"
    }
   ]
  },
  {
   "title": "Change",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data = from(bucket: \"amaroq\")\n  |> range(start: 2023-01-10T21:08:38.211Z, stop: 2023-01-20T21:08:38.211Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"amaroq_results_stateful\")\n  |> filter(fn: (r) => r[\"_value\"] == \"new\" or\n    r[\"_value\"] == \"updated\"  or\n    r[\"_value\"] == \"unchanged\"  or\n    r[\"_value\"] == \"absent\" )\n  \ndata\n  |> group(columns: [\"_value\"])|> set(key: \"Count\", value: \"_value\")|> count(column: \"Count\")"
    }
   ]
  },
  {
   "title": "Change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"amaroq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"amaroq_runs\")\n  //|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")"
    }
   ]
  },
  {
   "title": "Change",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"amaroq\")\n  |> range(start: 2023-01-10T21:08:38.211Z, stop: 2023-01-20T21:08:38.211Z)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"amaroq_results_stateful\")\n  |> filter(fn: (r) => r[\"_field\"] == \"baseline_state\")\n  |> group()\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")  "
    }
   ]
  },
  {
   "title": "Change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"amaroq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn:(r) => r._measurement == \"amaroq_results\")\n  |> filter(fn: (r) => r._field == \"_time\" or r._field == \"baseline_state\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> group(columns: [\"baseline_state\", \"_time\"])\n  |> set(key: \"Count\", value: \"baseline_state\")|> count(column: \"Count\")  \n  |> pivot(rowKey:[\"_time\"], columnKey:[\"baseline_state\"], valueColumn:\"Count\")\n  \n  "
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "query": "SELECT SUM(\"total\") AS \"total\", SUM(\"critical\") AS \"critical\", SUM(\"high\") AS \"high\" FROM \"amaroq-results\" WHERE \"organizationId\" = 'bbae556c-35f0-469b-8d36-c168c012f9ca' and  \"projectId\" = 'f170eac1-fd6c-44d3-8a3c-f914acc9339f'  ORDER BY time DESC LIMIT 1"
      },
      {}
     ]
    },
    {
     "title": "Totals",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "data = from(bucket: \"amaroq\")\n  //range\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //db\n  //|> filter(fn: (r) => r[\"_measurement\"] == \"totals\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"results\")\n  |> filter(fn: (r) => r[\"_value\"] == \"new\" or\n    r[\"_value\"] == \"updated\"  or\n    r[\"_value\"] == \"unchanged\"  or\n    r[\"_value\"] == \"absent\" )\n  \n  \n  //where\n  //|> filter(fn: (r) => r.baselineState != \"new\")\n//  |> last()\n\ndata\n  |> group(columns: [\"_value\"])|> set(key: \"Count\", value: \"_value\")|> count(column: \"Count\")\n  |> last()  "
      }
     ]
    },
    {
     "title": "Current Totals",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "query": "data = from(bucket: \"amaroq\")\n  //range\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  //db\n  |> filter(fn: (r) => r[\"_measurement\"] == \"totals\")\n  \n  //where\n  //|> filter(fn: (r) => r.baselineState != \"new\")\n\n  //fields\n  //|> filter(fn: (r) => r._field == \"guid\")\n\n  |> last()\n  //|> yield(name: \"guid\")\n\ndata\n  |> filter(fn: (r) => r._field == \"updated\")\n  |> yield(name: \"updated\")\n\ndata\n  |> filter(fn: (r) => r._field == \"new\")\n  |> yield(name: \"new\")\n  \ndata\n  |> filter(fn: (r) => r._field == \"absent\")\n  |> yield(name: \"absent\")  \n\ndata\n  |> filter(fn: (r) => r._field == \"unchanged\")\n  |> yield(name: \"unchanged\")  \n\n\ndata \n  \n\ndata\n    |> group(columns: [\"new\", \"abset\", \"updated\", \"unchanged\"])\n\n"
      }
     ]
    }
   ]
  }
 ]
}